### ISSUE TITLE
[HELP] What is the difference between the many docker image variants?

### ISSUE THREAD

**Issue by leonardoraele** [sitespeedio/sitespeed.io-docker#18]
There are four variants of the 17.6.0 image:

- `sitespeedio/sitespeed.io:17.6.0-webpagetest`
- `sitespeedio/sitespeed.io:17.6.0-slim`
- `sitespeedio/sitespeed.io:17.6.0-plus1`
- `sitespeedio/sitespeed.io:17.6.0`

What is the difference between them? (please add this information to the README.md file)

**Comment by soulgalore** [comment]
Hi @leonardoraele sorry for the confusion (let me deprecate this repo since it's old). We have the info today but on different places on https://www.sitespeed.io.

* sitespeedio/sitespeed.io:17.6.0 - the default container including sitespeed.io and using browsertime as engine. Including.three browsers: Chrome, Firefox and Edge.Also includes software to record a video of the screen and calculate visual metrics.

* sitespeedio/sitespeed.io:17.6.0-slim - the smallest container only container sitespeed.io and Firefox. 
* sitespeedio/sitespeed.io:17.6.0-plus1 - the same as sitespeedio/sitespeed.io:17.6.0  + including plugins for Google tools: PSI and Lighthouse
* sitespeedio/sitespeed.io:17.6.0-webpagetest -  the same as sitespeedio/sitespeed.io:17.6.0  + including the WebPageTest plugin.

**Comment by leonardoraele** [comment]
@soulgalore Great! Thanks for the clarification
