### ISSUE TITLE
Docker container on mac m1 always runs tests on Chromium 107 

### ISSUE THREAD

**Issue by nilanjansiromani** [sitespeedio/sitespeed.io-docker#19]
Docker container on mac m1 always runs tests on Chromium 107 
Please see the log below
```
❯ docker run --privileged --shm-size=1g --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io http://www.sitespeed.io/ -b chrome

Chromium 107.0.5304.62 Ubuntu 22.04
Mozilla Firefox 117.0
[2023-09-09 12:44:21] INFO: Versions OS: linux 5.15.49-linuxkit nodejs: v18.16.0 sitespeed.io: 29.5.0 browsertime: 17.16.0 coach: 8.0.2
[2023-09-09 12:44:21] INFO: Running tests using Chrome - 3 iteration(s)
[2023-09-09 12:44:22] INFO: Testing url http://www.sitespeed.io/ iteration 1
```

**Comment by soulgalore** [comment]
Hi @nilanjansiromani thanks for creating the issue! There's no official build for Chrome/Chromium on ARM there's some explanation here https://www.sitespeed.io/documentation/sitespeed.io/docker/#running-on-mac-m1-arm so that container will always using older versions. If you can try the Rosetta emulation explained in the documentation.

**Comment by nilanjansiromani** [comment]
Thanks !
